spring.application.name=auth-sphere-jwt

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/auth_jwt_db
spring.datasource.username=root
spring.datasource.password=rootroot

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework.security=DEBUG
